matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - pip install git+https://github.com/joerick/cibuildwheel@c3565d5025566dcf4b795eef8d40f38a12872151
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/pcst_fast-*.whl
    fi
env:
  global:
    - CIBW_SKIP=cp26-* cp27-* cp34-*
    - TWINE_USERNAME=zfrenchee
      # Note: TWINE_PASSWORD is set in Travis settings
